export const MenuRestaurant = [
  {
    id: "main_dish",
    title: "Main dish",
    foods: [
      {
        name: "Prime steak",
        price: "49'000₮",
        description: ["Beef tenderlion, Mush, Vegetables, Sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Primeat ribeye steak",
        price: "69'000₮",
        description: ["Mush, Salsa, Sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Primeat serlion steak",
        price: "79'000₮",
        description: ["Wedget potato, Carrot, Saice"],
        // path: "/set/s_set.png",
      },
      {
        name: "Steak pasta",
        price: "34'000₮",
        description: ["Tagliatelle, Beef tenderlion steak"],
        // path: "/set/s_set.png",
      },
      {
        name: "Sphagetti alla carbonara",
        price: "29'000₮",
        description: ["Parmesan cheese, sphagetti pasta, egg yolk"],
        // path: "/set/s_set.png",
      },
      {
        name: "Pork short ribs",
        price: "39'000₮",
        description: ["BBQ sauce, Wedge potato, vegetables"],
        // path: "/set/s_set.png",
      },
      {
        name: "Chicken bowl",
        price: "28'000₮",
        description: ["Chicken thigh meat, Egg, Carrot salad"],
        // path: "/set/s_set.png",
      },
      {
        name: "Chicken fajitas",
        price: "31'000₮",
        description: ["Chicken thigh meat, Cream, Sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Chicken marined",
        price: "34'000₮",
        description: ["Chicken thighs meat, Onion, Sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Beef ribs",
        price: "34'000₮",
        description: ["Beef short ribs, Mush, Vegetables"],
        // path: "/set/s_set.png",
      },
      {
        name: "Salmon steak",
        price: "65'000₮",
        description: ["Creamy mushes, Asparagus"],
        // path: "/set/s_set.png",
      },
      {
        name: "Chips and fish",
        price: "25'000₮",
        description: ["Tilapia, French fries, Mayo sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Buuz",
        price: "26'000₮",
        description: ["Lamb, Vegetable, Salad"],
        // path: "/set/s_set.png",
      },
      {
        name: "Khuushuur",
        price: "26'000₮",
        description: ["Beef, Vegetable, Salad"],
        // path: "/set/s_set.png",
      },
      {
        name: "Tsuiwan /өвчүүтэй/",
        price: "28'000₮",
        description: ["Beef, Vegetable"],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "burger_pizza",
    title: "Burger & Pizza",
    foods: [
      {
        name: "Prime burger",
        price: "34'000₮",
        description: ["Beef meat, Cheese, Sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "BBQ burger",
        price: "29'000₮",
        description: ["Beef meat, Cheddar, Mozerella cheese, BBQ sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Margherita",
        price: "37'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Hawai pizza",
        price: "36'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "The meat matrix",
        price: "39'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "share_food",
    title: "SHARE FOOD",
    foods: [
      {
        name: "Grill platter",
        price: "125'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Chicken platter",
        price: "100'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "salad",
    title: "SALAD",
    foods: [
      {
        name: "Summer /Greek/",
        price: "22'000₮",
        description: ["Fetaki cheese, Cherry, Salad leaves, Fruits, Cucumber"],
        // path: "/set/s_set.png",
      },
      {
        name: "Winter /Caesar/",
        price: "28'000₮",
        description: ["Iceberg, Tortilla, Parmesan, Sauce"],
        // path: "/set/s_set.png",
      },
      {
        name: "Autumn /Chicken cobb/",
        price: "28'000₮",
        description: ["Avacoda, Cherry, Bacon, Egg, Chicken breast"],
        // path: "/set/s_set.png",
      },
      {
        name: "Spring /Steak salad/",
        price: "28'000₮",
        description: ["Beef tenderlion steak, Salad Leaves, Cherry, Olive"],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "slide_dish",
    title: "SLIDE DISH",
    foods: [
      {
        name: "Fried rice",
        price: "11'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Fried rice",
        price: "10'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Salsa with nachos",
        price: "24'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "French fries with salsa",
        price: "16'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "French fries",
        price: "13'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Garlic bread",
        price: "12'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "soup",
    title: "SOUP",
    foods: [
      {
        name: "Khuushuur soup",
        price: "22'000₮",
        description: ["Ясны шөл, Хоньны мах, Үхрийн махтай хуушуур"],
        // path: "/set/s_set.png",
      },
      {
        name: "Dumpling with soup",
        price: "23'000₮",
        description: ["Bone soup, dumpling, lamb meat"],
        // path: "/set/s_set.png",
      },
      {
        name: "Chicken rosemary soup",
        price: "21'000₮",
        description: ["Chicken thighs meat, Rosemary, Vegetables"],
        // path: "/set/s_set.png",
      },
      {
        name: "Beef marrow soup",
        price: "31'000₮",
        description: ["Healthy vegetables"],
        // path: "/set/s_set.png",
      },
      {
        name: "Chicken spicy soup",
        price: "41'000₮",
        description: ["Chicken thigh meat, carrot, mushroom, onion"],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "dessert",
    title: "DESSERT",
    foods: [
      {
        name: "Red velvet",
        price: "26'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Carrot cake",
        price: "27'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Choc it to me",
        price: "26'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Tiramisu",
        price: "28'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "tea_coffee",
    title: "TEA & COFFEE",
    foods: [
      {
        name: "Pot tea",
        price: "11'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Tea",
        price: "2'500₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Ice tea",
        price: "9'500₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Prime coffee",
        price: "6'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Irish coffee",
        price: "26'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Latte",
        price: "8'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Latte caramel",
        price: "9'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Latte vanilla",
        price: "9'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Ice americano",
        price: "7'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Espresso",
        price: "98000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "tea_coffee",
    title: "SOFT DRINK",
    foods: [
      {
        name: "Soft",
        price: "6'500₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Khujirt",
        price: "4'200₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Red bull",
        price: "8'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Juice 250ml",
        price: "5'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "cocktail",
    title: "COCKTAIL",
    foods: [
      {
        name: "Gin tonic",
        price: "20'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Negroni",
        price: "28'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Martini",
        price: "28'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Whisky sour",
        price: "25'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Long island",
        price: "28'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Tequila sunrise",
        price: "22'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Jäger bomb",
        price: "20'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "beer",
    title: "BEER",
    foods: [
      {
        name: "Tsingtao",
        price: "10'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Cass",
        price: "10'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Kaltenberg",
        price: "12'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "GEM draft",
        price: "11'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Corona",
        price: "12'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Kirin ichiban",
        price: "10'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Heineken",
        price: "10'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Asahi",
        price: "14'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "gin",
    title: "GIN",
    foods: [
      {
        name: "Bombay",
        price: "220'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Gordons",
        price: "12'500 / 150'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "wine",
    title: "WINE",
    foods: [
      {
        name: "Maison castel s/b",
        price: "23'000₮ / 85'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Maison castel merlot",
        price: "22'000₮ / 80'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Maison castel chardonney",
        price: "23'000₮ / 85'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "LA baume chardonney",
        price: "120'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "LA baume cabernet",
        price: "120'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Calvet / Cinsault",
        price: "75'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "whiskey",
    title: "WHISKEY",
    foods: [
      {
        name: "Glenmorangie",
        price: "360'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Jack Daniels",
        price: "15'000₮ / 250'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Jameson",
        price: "17'000₮ / 250'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Chivas",
        price: "260'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Johnny Walker Red",
        price: "11'500₮ / 160'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Johnny Walker Black",
        price: "260'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "cognac",
    title: "COGNAC",
    foods: [
      {
        name: "Martell",
        price: "510'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Hennessy V.S.O.P",
        price: "500'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Hennessy V.S",
        price: "25'000₮ / 380'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "vodka",
    title: "VODKA",
    foods: [
      {
        name: "Grey Goose",
        price: "320'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Beluga",
        price: "320'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Finlandia",
        price: "12'000₮ / 160'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Evok",
        price: "110'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Eden",
        price: "8'000₮ / 80'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Absolute",
        price: "12'000₮ / 160'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "Liqueur",
    title: "LIQUEUR",
    foods: [
      {
        name: "Jägermeister",
        price: "320'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Balleys",
        price: "10'000₮ / 150'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
  {
    id: "tequila",
    title: "TEQUILA",
    foods: [
      {
        name: "Sierra (Silver)",
        price: "14'000₮ / 150'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
      {
        name: "Sierra (Gold)",
        price: "14'000₮ / 150'000₮",
        description: [""],
        // path: "/set/s_set.png",
      },
    ],
  },
];
